- name: Install WG route service
  template:
    src: wg-route.service.j2
    dest: /etc/systemd/system/wg-route.service
    mode: "0644"

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Enable WG route service
  systemd:
    name: wg-route.service
    enabled: true

- name: Reset failed WG route service state
  command: systemctl reset-failed wg-route.service
  failed_when: false
  changed_when: false

- name: Start WG route service
  systemd:
    name: wg-route.service
    state: restarted
