name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - terraform/backend.tf

concurrency:
  group: production-deploy
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Read Terraform Outputs
        working-directory: terraform
        id: tf
        run: |
          echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy
        env:
          VM_IP: ${{ steps.tf.outputs.public_ip }}
          SSH_USER: azureuser
          REPO_NAME: ${{ github.event.repository.name }}

        run: |
          ssh -o StrictHostKeyChecking=no \
            ${SSH_USER}@${VM_IP} <<EOF
          set -e

          cd /opt/${REPO_NAME}
          git pull origin main
          set -a
          if [ ! -f .bootstrap.env ]; then
          echo ".bootstrap.env not found"
          exit 1
          fi

          cd /opt/${REPO_NAME}

          git pull origin main

          cd ansible

          ansible-playbook \
            -i inventory.ini \
            deploy.yml

          echo "Deployment completed."

          EOF
