name: Update Auth Password

on:
  workflow_dispatch:

jobs:
  update-auth:
    runs-on: ubuntu-latest

    steps:

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATEKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Update htpasswd
        env:
          VM_IP: ${{ secrets.VM_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}

          NGINX_BASIC_AUTH_USER: ${{ secrets.NGINX_BASIC_AUTH_USER }}
          NGINX_BASIC_AUTH_PASSWORD: ${{ secrets.NGINX_BASIC_AUTH_PASSWORD }}

          REPO_NAME: ${{ github.event.repository.name }}

        run: |
          ssh -o StrictHostKeyChecking=no \
          ${SSH_USER}@${VM_IP} <<EOF

          set -e

          BOOTSTRAP_FILE=\$(find /opt -maxdepth 2 -name ".bootstrap.env" | head -n 1)

          if [ -z "\$BOOTSTRAP_FILE" ]; then
            echo ".bootstrap.env not found"
            exit 1
          fi

          export REPO_NAME="${REPO_NAME}"



          cd /opt/${REPO_NAME}

          htpasswd -bc \
          /opt/${REPO_NAME}/nginx/.htpasswd \
          "${NGINX_BASIC_AUTH_USER}" \
          "${NGINX_BASIC_AUTH_PASSWORD}"


          echo ".htpasswd updated"
          EOF
